apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  config.toml: |
    [pool]
    size = 10000
    
    [redis]
    host = "redis"
    port = "6379"
    
    [kafka]
    brokers = ["kafka:9092"]
    topics = ["orders"]
    topic = "orders"
    group = "match"
